"""empty message

Revision ID: d2650f352fc6
Revises: 454a6b738974
Create Date: 2020-10-27 14:57:22.489711

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2650f352fc6'
down_revision = '454a6b738974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lists', 'date_created',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP(6)'))
    op.create_unique_constraint(None, 'lists', ['name'])
    op.alter_column('tasks', 'completed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('tasks', 'date_created',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP(6)'))
    op.alter_column('tasks', 'end_date',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'date_created',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP(6)'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'date_created',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP(6)'))
    op.alter_column('tasks', 'end_date',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tasks', 'date_created',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP(6)'))
    op.alter_column('tasks', 'completed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_constraint(None, 'lists', type_='unique')
    op.alter_column('lists', 'date_created',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP(6)'))
    # ### end Alembic commands ###
