"""empty message

Revision ID: e7cbf243dfbc
Revises: d2650f352fc6
Create Date: 2020-10-27 16:18:55.091474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7cbf243dfbc'
down_revision = 'd2650f352fc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='lists')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'lists', ['name'], unique=True)
    # ### end Alembic commands ###
